"""Update domain models for JD-E8

Revision ID: 0dccf2e0916f
Revises: 31c8366aa88b
Create Date: 2026-05-25 17:59:51.701398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dccf2e0916f'
down_revision: Union[str, Sequence[str], None] = '31c8366aa88b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_research',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name_slug', sa.String(), nullable=False),
    sa.Column('research_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_research_company_name_slug'), 'company_research', ['company_name_slug'], unique=True)
    op.create_index(op.f('ix_company_research_id'), 'company_research', ['id'], unique=False)
    op.add_column('applications', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('cover_letters', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('cover_letters', sa.Column('ats_score', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cover_letters_user_id'), 'cover_letters', ['user_id'], unique=False)
    op.drop_column('cover_letters', 'ats_keyword_match')
    op.add_column('cvs', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('cvs', sa.Column('filename', sa.String(), nullable=True))
    op.add_column('cvs', sa.Column('embedding_status', sa.Enum('pending', 'processing', 'ready', 'failed', name='cvembeddingstatus', native_enum=False), nullable=False))
    op.create_index(op.f('ix_cvs_user_id'), 'cvs', ['user_id'], unique=False)
    op.add_column('jobs', sa.Column('company_slug', sa.String(), nullable=True))
    op.add_column('recruiters', sa.Column('interaction_score', sa.Integer(), nullable=False))
    op.add_column('recruiters', sa.Column('notes', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'recruiters', ['linkedin_url'])
    op.drop_column('recruiters', 'scraped_at')
    op.drop_column('recruiters', 'quality_score')
    op.add_column('scrape_runs', sa.Column('errors', sa.Integer(), nullable=False))
    op.add_column('scrape_runs', sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('scrape_runs', 'run_at')
    op.add_column('user_profiles', sa.Column('target_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('user_profiles', sa.Column('preferred_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('user_profiles', sa.Column('seniority_level', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('target_salary_min', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('target_salary_max', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('preferred_location', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('notice_period', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'notice_period')
    op.drop_column('user_profiles', 'preferred_location')
    op.drop_column('user_profiles', 'target_salary_max')
    op.drop_column('user_profiles', 'target_salary_min')
    op.drop_column('user_profiles', 'seniority_level')
    op.drop_column('user_profiles', 'preferred_stack')
    op.drop_column('user_profiles', 'target_roles')
    op.add_column('scrape_runs', sa.Column('run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('scrape_runs', 'ran_at')
    op.drop_column('scrape_runs', 'errors')
    op.add_column('recruiters', sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('recruiters', sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recruiters', type_='unique')
    op.drop_column('recruiters', 'notes')
    op.drop_column('recruiters', 'interaction_score')
    op.drop_column('jobs', 'company_slug')
    op.drop_index(op.f('ix_cvs_user_id'), table_name='cvs')
    op.drop_column('cvs', 'embedding_status')
    op.drop_column('cvs', 'filename')
    op.drop_column('cvs', 'user_id')
    op.add_column('cover_letters', sa.Column('ats_keyword_match', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_cover_letters_user_id'), table_name='cover_letters')
    op.drop_column('cover_letters', 'ats_score')
    op.drop_column('cover_letters', 'user_id')
    op.drop_column('applications', 'updated_at')
    op.drop_index(op.f('ix_company_research_id'), table_name='company_research')
    op.drop_index(op.f('ix_company_research_company_name_slug'), table_name='company_research')
    op.drop_table('company_research')
    # ### end Alembic commands ###
