"""Add SavedJob table

Revision ID: 31c8366aa88b
Revises: 0003
Create Date: 2026-05-25 17:52:24.018758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31c8366aa88b'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'user_id')
    )
    op.create_index(op.f('ix_saved_jobs_job_id'), 'saved_jobs', ['job_id'], unique=False)
    op.alter_column('applications', 'status',
               existing_type=postgresql.ENUM('draft', 'applied', 'awaiting_response', 'interviewing', 'offered', 'rejected', 'withdrawn', name='applicationstatus'),
               type_=sa.Enum('draft', 'applied', 'awaiting_response', 'interviewing', 'offered', 'rejected', 'withdrawn', name='applicationstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('cover_letters', 'status',
               existing_type=postgresql.ENUM('pending', 'generating', 'ready', 'failed', name='coverletterstatus'),
               type_=sa.Enum('pending', 'generating', 'ready', 'failed', name='coverletterstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('interview_preps', 'status',
               existing_type=postgresql.ENUM('pending', 'generating', 'ready', 'failed', name='interviewprepstatus'),
               type_=sa.Enum('pending', 'generating', 'ready', 'failed', name='interviewprepstatus', native_enum=False),
               existing_nullable=False)
    op.drop_column('jobs', 'saved')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('saved', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('interview_preps', 'status',
               existing_type=sa.Enum('pending', 'generating', 'ready', 'failed', name='interviewprepstatus', native_enum=False),
               type_=postgresql.ENUM('pending', 'generating', 'ready', 'failed', name='interviewprepstatus'),
               existing_nullable=False)
    op.alter_column('cover_letters', 'status',
               existing_type=sa.Enum('pending', 'generating', 'ready', 'failed', name='coverletterstatus', native_enum=False),
               type_=postgresql.ENUM('pending', 'generating', 'ready', 'failed', name='coverletterstatus'),
               existing_nullable=False)
    op.alter_column('applications', 'status',
               existing_type=sa.Enum('draft', 'applied', 'awaiting_response', 'interviewing', 'offered', 'rejected', 'withdrawn', name='applicationstatus', native_enum=False),
               type_=postgresql.ENUM('draft', 'applied', 'awaiting_response', 'interviewing', 'offered', 'rejected', 'withdrawn', name='applicationstatus'),
               existing_nullable=False)
    op.drop_index(op.f('ix_saved_jobs_job_id'), table_name='saved_jobs')
    op.drop_table('saved_jobs')
    # ### end Alembic commands ###
