"""Add interview_questions table

Revision ID: 8d3ba695e35f
Revises: e4672fe6a11b
Create Date: 2026-05-28 17:29:32.773092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d3ba695e35f'
down_revision: Union[str, Sequence[str], None] = 'e4672fe6a11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_metrics_agent_id'), 'eval_metrics', ['agent_id'], unique=False)
    op.create_index(op.f('ix_eval_metrics_id'), 'eval_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_eval_metrics_metric_name'), 'eval_metrics', ['metric_name'], unique=False)
    op.create_table('interview_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('interview_prep_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('difficulty_rating', sa.String(), nullable=False),
    sa.Column('suggested_answer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interview_prep_id'], ['interview_preps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_questions_id'), 'interview_questions', ['id'], unique=False)
    op.create_index(op.f('ix_interview_questions_interview_prep_id'), 'interview_questions', ['interview_prep_id'], unique=False)
    op.create_index(op.f('ix_interview_questions_job_id'), 'interview_questions', ['job_id'], unique=False)
    op.drop_column('saved_jobs', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_jobs', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_interview_questions_job_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_interview_prep_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_eval_metrics_metric_name'), table_name='eval_metrics')
    op.drop_index(op.f('ix_eval_metrics_id'), table_name='eval_metrics')
    op.drop_index(op.f('ix_eval_metrics_agent_id'), table_name='eval_metrics')
    op.drop_table('eval_metrics')
    # ### end Alembic commands ###
